---
# yamllint disable rule:line-length
name: Pre Commit

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  pre-commit:
    name: Pre Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install pre-commit dependencies
        run: |
          mkdir -p "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          TF_DOCS_VERSION="$(curl -sfSL https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | jq -r '.tag_name')"
          curl -sfSLo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/$TF_DOCS_VERSION/terraform-docs-$TF_DOCS_VERSION-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz terraform-docs
          chmod +x terraform-docs
          mv terraform-docs $HOME/.local/bin/

          TF_LINT_VERSION=$(curl -sfSL https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")
          curl -sfSL "$TF_LINT_VERSION" > tflint.zip
          unzip tflint.zip && rm tflint.zip
          mv tflint $HOME/.local/bin/
      - uses: pre-commit/action@v3.0.0
